name: Hourly Rental Scraping

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read # Required to list workflow runs and download artifacts

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Find latest successful workflow run
      id: find-run
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const workflowFileName = 'hourly_scrape.yml'; # The name of this workflow file

          console.log(`Searching for latest successful run of workflow '${workflowFileName}' in ${owner}/${repo}`);

          try {
            # List recent runs for this workflow
            const listRunsResponse = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: workflowFileName,
              branch: context.ref.replace('refs/heads/', ''), # Filter by current branch
              status: 'success', # Only consider successful runs
              per_page: 1, # We only need the most recent one
            });

            const latestSuccessfulRun = listRunsResponse.data.workflow_runs[0];

            if (latestSuccessfulRun) {
              console.log(`Found latest successful run: ID ${latestSuccessfulRun.id}`);
              core.setOutput('run_id', latestSuccessfulRun.id);
            } else {
              console.log(`No previous successful run found for workflow '${workflowFileName}' on branch '${context.ref.replace('refs/heads/', '')}'.`);
              core.setOutput('run_id', ''); # Output empty if no run found
            }

          } catch (error) {
            console.error('Error finding latest successful run:', error);
            core.setFailed(`Failed to find latest successful run: ${error.message}`);
          }

    - name: Download previous listings
      id: download-artifact
      uses: actions/download-artifact@v4
      # Continue on error in case no previous successful run was found or artifact expired
      continue-on-error: true
      if: steps.find-run.outputs.run_id != '' # Only attempt download if a run_id was found
      with:
        name: listings
        path: .
        run-id: ${{ steps.find-run.outputs.run_id }} # Use the found run_id

    # Initialize listings file if download failed or no previous run was found
    - name: Initialize listings file if not downloaded
      # This step runs if the download step was skipped (no run_id) or if it failed
      if: steps.find-run.outputs.run_id == '' || steps.download-artifact.outcome != 'success'
      run: |
        echo "[]" > listings.json
        echo "Initialized new empty listings.json file."

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 discord.py

    - name: Run scraper
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      run: python main.py

    - name: Upload new listings
      uses: actions/upload-artifact@v4
      with:
        name: listings
        path: listings.json
        retention-days: 30
