name: Hourly Rental Scraping

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download previous listings
      id: download-artifact
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: listings
        github-token: ${{ secrets.GITHUB_TOKEN }} # Required to fetch artifacts from other runs
        workflow: Hourly Rental Scraping          # Specify the workflow name
        path: .                                   # Download to the current directory

    - name: List files after download # Added for debugging
      run: ls -R

    - name: Check if listings.json exists # Added for debugging
      run: |
        if [ -f listings.json ]; then
          echo "listings.json exists after download!"
        else
          echo "listings.json does NOT exist after download."
        fi

    - name: Initialize listings file
      run: |
        if [ ! -f listings.json ]; then
          echo "[]" > listings.json
          echo "Created empty listings.json file." # Added logging
        else
          echo "listings.json already exists." # Added logging
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 discord.py

    - name: Run scraper
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      run: python main.py

    - name: Upload new listings
      uses: actions/upload-artifact@v4
      with:
        name: listings
        path: listings.json
        retention-days: 30