name: Hourly Rental Scraping

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Try to download previous artifact
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: listings
        path: .
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Initialize listings file
      run: |
        if [ ! -f listings.json ]; then
          echo "[]" > listings.json
          echo "Created new empty listings.json file"
        else
          echo "Using existing listings.json file"
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 discord.py

    - name: Run scraper
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      run: python main.py

    - name: Upload listings artifact
      uses: actions/upload-artifact@v4
      with:
        name: listings
        path: listings.json
        retention-days: 30
        overwrite: true
